import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const input = [2, 5, 8, 6];
  const output = input.reduce((prev, current) => {
    return prev + current;
  });

  const input2 = [
    { name: "pople1", age: 10 },
    { name: "pople2", age: 20 },
    { name: "pople3", age: 30 },
    { name: "pople4", age: 40 },
  ];

  const output2 = input2.reduce((prev, current) => {
    return prev + current.age;
  }, 0);

  const input3 = [
    { name: "pople1", age: 10 },
    { name: "pople2", age: 20 },
    { name: "pople3", age: 10 },
    { name: "pople4", age: 20 },
  ];

  const output3 = input3.reduce((prev, current) => {
    console.log({ prev, current });
    //{10:["pople1,"pople3"],20:["pople2,"pople4"]}
    return {
      ...prev,
      [current.age]: prev[current.age]
        ? [...prev[current.age], current.name]
        : [current.name],
    };
  }, {});
  console.log(output3);
  return (
    <div className={styles.container}>
      <Head>
        <title>Reduce関数</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Reduce関数</h1>

        <p className={styles.description}>Reduce関数について一覧</p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>足し算していく簡単な出し方</h2>
            <p>const input=[2,5,8,6]</p>
            <p>return prev + current;</p>

            <p>{output}</p>
          </div>

          <div className={styles.card}>
            <h2>Ageを求めよ</h2>
            <p>
              name: "pople1" age: 10
              <br />
              name: "pople2" age: 20
              <br />
              name: "pople3" age: 30
              <br />
              name: "pople4" age: 40
            </p>
            <p>prev + current.age;</p>
            <p>初期値に0を入れる</p>
            <p>{output2}</p>
          </div>
          <div className={styles.card}>
            <h2>groupBy Age20の人 30の人を求めよ</h2>
            <p>
              name: "pople1" age: 10
              <br />
              name: "pople2" age: 20
              <br />
              name: "pople3" age: 10
              <br />
              name: "pople4" age: 20
            </p>
            <p>
              結果として
              <br /> 10:"pople1,"pople3"
              <br />
              20:"pople2,"pople4"と出したい。
            </p>
            <p>初期値に｛｝を入れる</p>
            <p> console.log(output3);で成功</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>Powered by Boo</footer>
    </div>
  );
}
